import basket1 from '../../images/evidences/others/basket/Basket1.jpg';

import metal1 from '../../images/evidences/others/metal/Metal1.jpg';
import metal2 from '../../images/evidences/others/metal/Metal2.jpg';
import metal3 from '../../images/evidences/others/metal/Metal3.jpg';

import nfc from '../../images/evidences/others/nfc/nfc.jpg';

import tunner1 from '../../images/evidences/others/tunner/Tunner1.jpg';
import tunner2 from '../../images/evidences/others/tunner/Tunner2.jpg';


export const otherProjectsData = [
    {
        title: "Electrocardiogram",
        date: "2018",
        description: "This device was purely electronic components, the only coding used was to adapt LabView to read the signal. This was generally built using Operational Amplifiers.",
        link: "",
        video: "https://www.youtube.com/embed/_PWrSanaJpk",
        languages: "LabView",
        images: [nfc],
    },
    {
        title: "Basketball Arcade",
        date: "2017",
        description: "I have always loved the basketball arcade games, so I built one. Using an Arduino, an infrared sensor and some neat interrupt routines I made it work. Afterwards I added a small line so the basket could move to the front and to the sides, for the complete experience. ",
        link: "",
        video: "https://www.youtube.com/embed/-jpZEWNrnXk",
        languages: "C++",
        images: [basket1],
    },
    {
        title: "NFC Reader",
        date: "2018",
        description: "To fight against the mess of college events I built an NFC reader to maintain a database were I kept all the attendees to events. This database was linked to a webpage to be able to see and manipulate the data.  ",
        link: "",
        video: "https://www.youtube.com/embed/dMpzWBYmNKA",
        languages: "C++, PHP, Html, Javascript",
        images: [nfc],
    },
    {
        title: "Auto Tunner",
        date: "2017",
        description: "This device was capable of tunning automatically any string instrument. The interface was with LabView and the rest was pure electronics and a few minor things with an Arduino Nano. ",
        link: "",
        video: "",
        languages: "LabView, C++",
        images: [tunner1, tunner2],
    },
    {
        title: "Metal Detector",
        date: "2017",
        description: "I like rocks and good grades, so taking these two things together I built as a project a metal detector capable of detecting how much metal is near and how near it was. Again I took advantage of interrupts to read the wave generated by the electronic components. ",
        link: "",
        video: "https://www.youtube.com/embed/cX2SaoPmQx0",
        languages: "C++",
        images: [metal1, metal2, metal3],
    },
];
